server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password:
